/*
 * GUI Agend
 */
package com.agenda.gui;

import com.agenda.entity.Subscriber;
import com.agenda.entity.Phone;
import com.agenda.controller.CarteDeTelefon;
import com.agenda.exceptions.IdenticalMembersException;
import com.agenda.filecontrol.FileHandler;
import com.agenda.filecontrol.FileReader;
import com.agenda.filecontrol.FileWriter;
import com.agenda.login.LogIn;
import com.agenda.types.ActionTypes;
import com.agenda.types.OrderTypes;
import com.agenda.model.ModelTabel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.SplashScreen;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.Timer;

/**
 *
 * @author Elena Ionita
 */
public class Agenda extends javax.swing.JFrame {

    static ResultSet resultSet = null;
    CarteDeTelefon carteDeTelefon;
    Timer addsTimer;
    Timer autosaveTimer;
    Point rightMouseClick;
    private Object tableView;
    
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
                initPopUp();
        tableView.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_DELETE){
                    int answer = JOptionPane.showConfirmDialog((Component) tableView, "You want to delete a subscriber?");
                    if(answer == 0){
                      int row = tableView.getSelectedRow();
                      Subscriber subscriber = modelTabel.getListSubscribers().get(row);
                      carteDeTelefon.removeSubscriber(subscriber);
                    }
                    updateGUI();
                }
            }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jRadioButtonFileOpen = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonFileSave = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonFileExit = new javax.swing.JRadioButtonMenuItem();
        subscriberMenu = new javax.swing.JMenu();
        jRadioButtonSubscriberAdd = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonSubscriberEdit = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonSubcriberSearch = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonSubscriberDelete = new javax.swing.JRadioButtonMenuItem();
        helpMenu = new javax.swing.JMenu();
        jRadioButtonHelpLogIn = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonHelpAbout = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "CNP", "Mobile No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMinWidth(3);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/search.png"))); // NOI18N
        jPanel2.add(jLabel1);

        jTextFieldSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldSearch);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSearch);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset);

        jButtonAdd.setText("Add");
        jButtonAdd.setPreferredSize(new java.awt.Dimension(55, 23));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonRemove.setText("Remove");
        jButtonRemove.setPreferredSize(new java.awt.Dimension(55, 23));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButton1.setText("First name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Last name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CNP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mobile No.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/sort_descending.png"))); // NOI18N
        jLabel2.setText("Sort by:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/phone-book-icone-4703-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEdit)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(109, 109, 109)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap())
        );

        fileMenu.setText("File");
        fileMenu.setPreferredSize(new java.awt.Dimension(30, 19));

        jRadioButtonFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonFileOpen.setSelected(true);
        jRadioButtonFileOpen.setText("Open");
        jRadioButtonFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/open-icon.png"))); // NOI18N
        jRadioButtonFileOpen.setPreferredSize(new java.awt.Dimension(200, 22));
        jRadioButtonFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFileOpenActionPerformed(evt);
            }
        });
        fileMenu.add(jRadioButtonFileOpen);

        jRadioButtonFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonFileSave.setSelected(true);
        jRadioButtonFileSave.setText("Save");
        jRadioButtonFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/save.png"))); // NOI18N
        jRadioButtonFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFileSaveActionPerformed(evt);
            }
        });
        fileMenu.add(jRadioButtonFileSave);
        fileMenu.add(jSeparator1);

        jRadioButtonFileExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonFileExit.setSelected(true);
        jRadioButtonFileExit.setText("Exit");
        jRadioButtonFileExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/application_exit.png"))); // NOI18N
        jRadioButtonFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFileExitActionPerformed(evt);
            }
        });
        fileMenu.add(jRadioButtonFileExit);

        jMenuBar.add(fileMenu);

        subscriberMenu.setText("Subscriber");
        subscriberMenu.setPreferredSize(new java.awt.Dimension(70, 19));

        jRadioButtonSubscriberAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jRadioButtonSubscriberAdd.setSelected(true);
        jRadioButtonSubscriberAdd.setText("Add ");
        jRadioButtonSubscriberAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/user_male_add.png"))); // NOI18N
        jRadioButtonSubscriberAdd.setPreferredSize(new java.awt.Dimension(200, 22));
        jRadioButtonSubscriberAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSubscriberAddActionPerformed(evt);
            }
        });
        subscriberMenu.add(jRadioButtonSubscriberAdd);

        jRadioButtonSubscriberEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jRadioButtonSubscriberEdit.setSelected(true);
        jRadioButtonSubscriberEdit.setText("Edit");
        jRadioButtonSubscriberEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/edit.png"))); // NOI18N
        jRadioButtonSubscriberEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSubscriberEditActionPerformed(evt);
            }
        });
        subscriberMenu.add(jRadioButtonSubscriberEdit);

        jRadioButtonSubcriberSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jRadioButtonSubcriberSearch.setSelected(true);
        jRadioButtonSubcriberSearch.setText("Search");
        jRadioButtonSubcriberSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/search.png"))); // NOI18N
        jRadioButtonSubcriberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSubcriberSearchActionPerformed(evt);
            }
        });
        subscriberMenu.add(jRadioButtonSubcriberSearch);

        jRadioButtonSubscriberDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jRadioButtonSubscriberDelete.setSelected(true);
        jRadioButtonSubscriberDelete.setText("Delete");
        jRadioButtonSubscriberDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/delete.png"))); // NOI18N
        jRadioButtonSubscriberDelete.setPreferredSize(new java.awt.Dimension(115, 22));
        jRadioButtonSubscriberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSubscriberDeleteActionPerformed(evt);
            }
        });
        subscriberMenu.add(jRadioButtonSubscriberDelete);

        jMenuBar.add(subscriberMenu);

        helpMenu.setText("Help");
        helpMenu.setPreferredSize(new java.awt.Dimension(50, 19));

        jRadioButtonHelpLogIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonHelpLogIn.setSelected(true);
        jRadioButtonHelpLogIn.setText("Log in");
        jRadioButtonHelpLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/key.png"))); // NOI18N
        jRadioButtonHelpLogIn.setPreferredSize(new java.awt.Dimension(200, 22));
        jRadioButtonHelpLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHelpLogInActionPerformed(evt);
            }
        });
        helpMenu.add(jRadioButtonHelpLogIn);
        helpMenu.add(jSeparator2);

        jRadioButtonHelpAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonHelpAbout.setSelected(true);
        jRadioButtonHelpAbout.setText("About");
        jRadioButtonHelpAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurces/icons/Get info.png"))); // NOI18N
        jRadioButtonHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHelpAboutActionPerformed(evt);
            }
        });
        helpMenu.add(jRadioButtonHelpAbout);

        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFileExitActionPerformed
            int answer = JOptionPane.showConfirmDialog(this, "You want to save before exit?");
        if(answer==0){
            carteDeTelefon.savePhonebook();
            System.exit(0);
        }else {
            System.exit(0);
        }
    }//GEN-LAST:event_jRadioButtonFileExitActionPerformed

    private void jRadioButtonFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFileOpenActionPerformed
            int answer = JOptionPane.showConfirmDialog(this, "You want to open a file?");
        if(answer == 1){
            carteDeTelefon.openPhonebook(true);
        }
        if(answer == 0){
            carteDeTelefon.openPhonebook(false);
        }
        updateGUI();
    }//GEN-LAST:event_jRadioButtonFileOpenActionPerformed

    private void jRadioButtonSubscriberEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSubscriberEditActionPerformed
            int index = this.tableView.getSelectedRow();
        if(index>=0){
            SubscriberView addSubscriberView = new SubscriberView();
            Subscriber oldSubscriber = modelTabel.getListSubscribers().get(index);
            addSubscriberView.firstNameField.setText(oldSubscriber.getFirstName());
            addSubscriberView.lastNameField.setText(oldSubscriber.getLastName());
            addSubscriberView.cnpField.setText(oldSubscriber.getCnp());
            addSubscriberView.phoneField.setText(oldSubscriber.getMobileNo().getPhone());
            if(JOptionPane.showConfirmDialog(null, addSubscriberView.getAddSubscriberPanel(),"Edit the subscriber info.", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                    Subscriber subscriber = new Subscriber(oldSubscriber.getId(), addSubscriberView.getFirstNameField().getText(), addSubscribertView.getLastNameField().getText(), 
                        addSubscriberView.getCnp().getText(), addSubscriberView.getPhoneField().getText(), false);
                    subscriber.setFromDb(true);
                try {
                    carteDeTelefon.editSubscriber(oldSubscriber, subscriber);
                    JOptionPane.showMessageDialog(this, "Successful edit!", "Edit", JOptionPane.INFORMATION_MESSAGE);
                    modelTabel.getListSubscribers().set(index, subscriber);
                } catch (IdenticalMembersException | IllegalArgumentException ex) {
                    Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
                }
                updateGUI();
            }
        }
        updateGUI();
    }//GEN-LAST:event_jRadioButtonSubscriberEditActionPerformed

    private void jRadioButtonSubscriberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSubscriberDeleteActionPerformed
            int answer = JOptionPane.showConfirmDialog(this, "You want to delete this subscriber?");
        if(answer == 0){
            int index = this.tableView.getSelectedRow();
            if(index>=0){
                Subscriber subscriber = modelTabel.getListSubscribers().get(index);
                carteDeTelefon.removeSubscriber(subscriber);
                modelTabel.getListSubscribers().remove(subscriber);
            }
        }
        updateGUI();
    }//GEN-LAST:event_jRadioButtonSubscriberDeleteActionPerformed

    private void jRadioButtonHelpLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHelpLogInActionPerformed
            String pass = JOptionPane.showInputDialog(this, "Please enter the password!", "Log in", JOptionPane.INFORMATION_MESSAGE);
        try{
            if(carteDeTelefon.register(pass)){
                addsTimer.stop();
                this.addsPanel.setVisible(!carteDeTelefon.isRegistered());
                this.fullVersion(carteDeTelefon.isRegistered());
            }
        }catch(NumberFormatException e){
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jRadioButtonHelpLogInActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
            List<Subscriber> temp = carteDeTelefon.search(this.searchField.getText());
        this.searchField.setText(null);
        if(temp.size()<carteDeTelefon.getListSubscribers().size()){
            this.resetButton.setBackground(Color.red);
        }
        modelTabel.setListSubscribers(temp);
        updateGUI();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        this.searchField.setText(null);
        this.resetButton.setBackground(this.searchButton.getBackground());
        modelTabel.setListSubscribers(carteDeTelefon.getListSubscribers());
        updateGUI();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
                SubscriberView addSubscriberView = new SubscriberView();
        if(JOptionPane.showConfirmDialog(null, addSubscriberView.getAddSubscriberPanel(),"Add a new subscriber.", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            try{
                Subscriber subscriber = new Subscriber(addSubscriberView.getFirstNameField().getText(), addSubscriberView.getLastNameField().getText(), 
                    addSubscriberView.getCnpField().getText(), addSubscriberView.getPhoneField().getText());
                carteDeTelefon.addSubscriber(subscriber);
                JOptionPane.showMessageDialog(this, "The new subscriber has been added!", "Add", JOptionPane.INFORMATION_MESSAGE);
            } catch (IdenticalMembersException | IllegalArgumentException ex) {
                Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
            }
        }
        updateGUI();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
                int answer = JOptionPane.showConfirmDialog(this, "You want to delete this subscriber?");
        if(answer == 0){
            int index = this.tableView.getSelectedRow();
            if(index>=0){
                Subscriber subscriber = modelTabel.getListSubscribers().get(index);
                carteDeTelefon.removeSubscriber(subscriber);
                modelTabel.getListSubscribers().remove(subscriber);
            }
        }
        updateGUI();
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
            if (evt.getButton() == MouseEvent.BUTTON3){
            rightMouseClick = this.tableView.getMousePosition();
            this.editPopUp.show(tableView, rightMouseClick.x, rightMouseClick.y);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jRadioButtonSubscriberAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSubscriberAddActionPerformed
            SubscriberView addSubscriberView = new SubscriberView();
        if(JOptionPane.showConfirmDialog(null, addSubscriberView.getAddSubscriberPanel(),"Add a new subscriber.", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            try{
                Subscriber subscriber = new Subscriber(addSubscriberView.getFirstNameField().getText(), addSubscriberView.getLastNameField().getText(), 
                    addSubscriberView.getCnpField().getText(), addSubscriberView.getPhoneField().getText());
                carteDeTelefon.addSubscriber(subscriber);
                JOptionPane.showMessageDialog(this, "The new subscriber has been added!", "Add", JOptionPane.INFORMATION_MESSAGE);
            } catch (IdenticalMembersException | IllegalArgumentException ex) {
                Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
            }
        }
        updateGUI();
    }//GEN-LAST:event_jRadioButtonSubscriberAddActionPerformed

    private void jRadioButtonHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHelpAboutActionPerformed
           JOptionPane.showMessageDialog(this, "Phonebook\nElena Ionita\n@2016", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButtonHelpAboutActionPerformed

    private void jRadioButtonFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFileSaveActionPerformed
            int answer = JOptionPane.showConfirmDialog(this, "You want to save the list?");
        if(answer == 0){
            carteDeTelefon.savePhonebook();
        }
    }//GEN-LAST:event_jRadioButtonFileSaveActionPerformed

    private void jRadioButtonSubcriberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSubcriberSearchActionPerformed
            List<Subscriber> temp = carteDeTelefon.search(this.searchField.getText());
        this.searchField.setText(null);
        if(temp.size()<carteDeTelefon.getListSubscribers().size()){
            this.resetButton.setBackground(Color.red);
        }
        modelTabel.setListSubscribers(temp);
        updateGUI();
    }//GEN-LAST:event_jRadioButtonSubcriberSearchActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
                int index = this.tableView.getSelectedRow();
        if(index>=0){
            SubscriberView addSubscriberView = new SubscriberView();
            Subscriber oldSubscriber = modelTabel.getListSubscribers().get(index);
            addSubscriberView.firstNameField.setText(oldSubscriber.getFirstName());
            addSubscriberView.lastNameField.setText(oldSubscriber.getLastName());
            addSubscriberView.cnpField.setText(oldSubscriber.getCnp());
            addSubscriberView.phoneField.setText(oldSubscriber.getMobileNo().getPhone());
            if(JOptionPane.showConfirmDialog(null, addSubscriberView.getAddSubscriberPanel(),"Edit the subscriber info.", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                    Subscriber subscriber = new Subscriber(oldSubscriber.getId(), addSubscriberView.getFirstNameField().getText(), addSubscribertView.getLastNameField().getText(), 
                        addSubscriberView.getCnp().getText(), addSubscriberView.getPhoneField().getText(), false);
                    subscriber.setFromDb(true);
                try {
                    carteDeTelefon.editSubscriber(oldSubscriber, subscriber);
                    JOptionPane.showMessageDialog(this, "Successful edit!", "Edit", JOptionPane.INFORMATION_MESSAGE);
                    modelTabel.getListSubscribers().set(index, subscriber);
                } catch (IdenticalMembersException | IllegalArgumentException ex) {
                    Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
                }
                updateGUI();
            }
        }
        updateGUI();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modelTabel.orderBy(OrderTypes.BY_FIRSTNAME);
        updateGUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            modelTabel.orderBy(OrderTypes.BY_LASTNAME);
        updateGUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        modelTabel.orderBy(OrderTypes.BY_CNP);
        updateGUI();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        modelTabel.orderBy(OrderTypes.BY_PHONE_NUMBER);
        updateGUI();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    /**
     * Initializare SplashScreen
     */
    
    public static void initSplashScreen() {
        SplashScreen splash = SplashScreen.getSplashScreen();
        Font font = new Font("Verdana", Font.BOLD, 12);
        Graphics2D mash = null;
        mash = splash.createGraphics();
        mash.setFont(font);
        mash.setColor(Color.GRAY);
        mash.fillRect(splash.getSize().width/3+25, splash.getSize().height/3, 250, 30);
        mash.setColor(Color.WHITE);
        mash.drawString("The phonebook is opening.", splash.getSize().width/3+35, splash.getSize().height/3 + 20);
        splash.update();
        try{
            Thread.sleep(300);
        }catch(InterruptedException e){
            
        }
        mash.setColor(Color.GRAY);
        mash.fillRect(splash.getSize().width/3+25, splash.getSize().height/3, 250, 30);
        mash.setColor(Color.WHITE);
        mash.drawString("Please wait.", splash.getSize().width/3+35, splash.getSize().height/3 + 20);
        splash.update();
        try{
            Thread.sleep(100);
        }catch(InterruptedException e){
            
        }
        mash.setColor(Color.GRAY);
        mash.fillRect(splash.getSize().width/3+25, splash.getSize().height/3, 250, 30);
        mash.setColor(Color.WHITE);
        mash.drawString("Loading...", splash.getSize().width/3+35, splash.getSize().height/3 + 20);
        splash.update();
        
        try{
            Thread.sleep(100);
        }catch(InterruptedException e){
            
        }
        mash.setColor(Color.GRAY);
        mash.fillRect(splash.getSize().width/3+25, splash.getSize().height/3, 250, 30);
        mash.setColor(Color.WHITE);
        mash.drawString("Loading...", splash.getSize().width/3+35, splash.getSize().height/3 + 20);
        splash.update();
        try{
            Thread.sleep(100);
        }catch(InterruptedException e){
            
        }
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonFileExit;
    private javax.swing.JRadioButtonMenuItem jRadioButtonFileOpen;
    private javax.swing.JRadioButtonMenuItem jRadioButtonFileSave;
    private javax.swing.JRadioButtonMenuItem jRadioButtonHelpAbout;
    private javax.swing.JRadioButtonMenuItem jRadioButtonHelpLogIn;
    private javax.swing.JRadioButtonMenuItem jRadioButtonSubcriberSearch;
    private javax.swing.JRadioButtonMenuItem jRadioButtonSubscriberAdd;
    private javax.swing.JRadioButtonMenuItem jRadioButtonSubscriberDelete;
    private javax.swing.JRadioButtonMenuItem jRadioButtonSubscriberEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JMenu subscriberMenu;
    // End of variables declaration//GEN-END:variables

}
